language: node_js
node_js:
  - "12"
  - "node"
cache:
  yarn: true
  directories:
    - .cache
    - node_modules
install:
  - npm ci
script:
  - npm run build --prefix-paths
git:
  depth: 25
  quiet: true
  on:
    branch: master